# Numpy Basics <br>
 <hr style = "border:2.5px Solid #126782"></hr>

Data Analyst: Chris Jomar A. Aurelio <br>
Department: Electrical Engineering

In [2]:
# imports and packages
import numpy as np
from scipy import stats

# 1D Array

In [4]:
array_a = np.array([1, 2, 3])
array_a

array([1, 2, 3])

# 2D Array

In [24]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
my_array = my_array.T

In [28]:
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [38]:
# add by row
np.sum(my_array, axis=0)

array([ 6, 15])

In [39]:
# add by column
np.sum(my_array, axis=1)

array([5, 7, 9])

# Measures of Central Tendency

In [2]:

fruits = np.array([120,60,85,150,200])
fruits


array([120,  60,  85, 150, 200])

In [3]:
# mean 
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [4]:
# median 
median_fruits = np.median(fruits)
median_fruits


np.float64(120.0)

In [8]:
# mode
mode_fruits = stats.mode(fruits)
mode_fruits


ModeResult(mode=np.int64(60), count=np.int64(1))

# Jaguar Vs Panther

In [42]:
jaguar = np.array([3,9.1,9.3,9.5,9.8,9.8,10.4,10.4,10.5,10.6,11])

In [5]:
panther = np.array([9.1,9.1,9.1,9.2,9.2,10.1,10.8,11,20])

# Jaguar

In [43]:
# mean Jaguar
mean_jaguar = np.mean(jaguar)
mean_jaguar

np.float64(9.4)

In [33]:
# median Jaguar
median_jaguar = np.median(jaguar)
median_jaguar

np.float64(9.8)

In [34]:
# mode Jaguar
mode_jaguar = stats.mode(jaguar)
mode_jaguar

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [44]:
max_jaguar = np.max(jaguar)
min_jaguar = np.min(jaguar)

range_jaguar = max_jaguar - min_jaguar
range_jaguar

np.float64(8.0)

In [47]:
# Quartile 1
q1_jaguar = np.percentile(jaguar, 25)
q1_jaguar

np.float64(9.4)

In [49]:
# Quartile 2
q2_jaguar = np.percentile(jaguar, 50)
q2_jaguar

np.float64(9.8)

In [50]:
# Quartile 3
q3_jaguar = np.percentile(jaguar, 75)
q3_jaguar

np.float64(10.45)

In [51]:
# IQR
iqr_jaguar = q3_jaguar - q1_jaguar
iqr_jaguar

np.float64(1.049999999999999)

In [55]:
# Sample Variance
var_jaguar = np.var(jaguar, ddof=1)
var_jaguar

np.float64(4.860000000000001)

In [56]:
# Sample Standard Deviation
std_jaguar = np.std(jaguar, ddof=1)
std_jaguar


np.float64(2.2045407685048604)

# Panther

In [35]:
# mean Panther
mean_panther = np.mean(panther)
mean_panther

np.float64(10.844444444444443)

In [36]:
# median Panther
median_panther = np.median(panther)
median_panther


np.float64(9.2)

In [37]:
# mode Panther
mode_panther = stats.mode(panther)
mode_panther

ModeResult(mode=np.float64(9.1), count=np.int64(3))

In [45]:
max_panther = np.max(panther)
min_panther = np.min(panther)

range_panther = max_panther - min_panther
range_panther

np.float64(10.9)

In [52]:
# Quartile 1
q1_panther = np.percentile(panther, 25)
q1_panther

np.float64(9.1)

In [53]:
# Quartile 2
q2_panther = np.percentile(panther, 50)
q2_panther

np.float64(9.2)

In [57]:
# Quartile 3
q3_panther = np.percentile(panther, 75)
q3_panther

np.float64(10.8)

In [59]:
# IQR
iqr_panther = q3_panther - q1_panther
iqr_panther

np.float64(1.700000000000001)

In [60]:
# Sample Variance
var_panther = np.var(panther, ddof=1)
var_panther

np.float64(12.36777777777778)

In [6]:
# Sample Standard Deviation
std_panther = np.std(panther, ddof=1)
std_panther


np.float64(3.516785148083087)